version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / a row perproduct found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: order_id
            description: id of the order
          - name: products_id
            description: id of the products
          - name: revenue
            description: turnover
          - name: quantity
            description: quantity sold
        freshness:
          warn_after: 
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null   
          - name: purchase_price
            description: price of products
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: logcost
          - name: ship_cost
                  
