version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / a row perproduct found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: order_id
            description: id of the order
          - name: products_id
            description: id of the products
          - name: revenue
            description: turnover
          - name: quantity
            description: quantity sold
        freshness:
          warn_after: 
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null   
          - name: purchase_price
            description: price of products
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: logcost
          - name: ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
  - name: intermediate
    tables:
      - name: sales_margin
        identifier: int_sales_margin
        description: calcule du purchase cost & de la marge
        columns:
          - name: orders_id
            description: number of the id
          - name: products_id
            description: id of the products
          - name: date_date
            description: la date
          - name: revenue
            description: le revenu du jour
          - name: quantity
            description: la quantité vendu
          - name: purchase_price
            description: prix
          - name: purchase_cost
            description: cout d'achat
          - name: margin
            description: marge du jour

